/*
 * Copyright (c) June 2024
 */
package com.ifms.javacalculator;

import java.awt.event.WindowEvent;

/**
 *
 * @author adhep
 */
public class JavaCalculator extends javax.swing.JFrame {

    /**
     * Creates new form JavaCalculator
     */
    public JavaCalculator() {
        initComponents();
        inputListener = new InputListener(jLabelDisplay, jLabelExpression);
        buttons = new CalcButton[]{
            new CalcButton(jButton1, "one", 0, "1", 0),
            new CalcButton(jButton6, "two", 0, "6", 0),
            new CalcButton(jButtonDiv, "div", 2, " / ", 8),
            new CalcButton(jButtonCloseBrack, "closeBrack", 4, ")", 0),
            new CalcButton(jButtonEuler, "euler", 1, "e^", 10),
            new CalcButton(jButtonSqrt, "sqrt", 1, "√", 10),
            new CalcButton(jButton2, "one", 0, "2", 0),
            new CalcButton(jButton7, "seven", 0, "7", 0),
            new CalcButton(jButtonPI, "pi", 3, "π", 0),
            new CalcButton(jButtonFact, "fact", 1, "!", 10),
            new CalcButton(jButtonDecPoint, "point", 6, ".", 0),
            new CalcButton(jButton9, "nine", 0, "9", 0),
            new CalcButton(jButtonClrAll, "clearAll", 4, "", 0),
            new CalcButton(jButtonInv, "inverse", 1, "1/", 10),
            new CalcButton(jButtonInvLog10, "antiLog", 1, "10^", 10),
            new CalcButton(jButtonSqr, "sqr", 1, "²", 10),
            new CalcButton(jButtonMult, "times", 2, " * ", 8),
            new CalcButton(jButtonPM, "pm", 5, "", 0),
            new CalcButton(jButtonOpenBrack, "openBrack", 4, "(", 11),
            new CalcButton(jButton3, "three", 0, "3", 0),
            new CalcButton(jButtonCos, "cosine", 1, "cos ", 10),
            new CalcButton(jButtonTan, "tangent", 1, "tan ", 10),
            new CalcButton(jButtonMinus, "minus", 2, " - ", 5),
            new CalcButton(jButtonExp, "exp", 2, " ^ ", 9),
            new CalcButton(jButton8, "eight", 0, "8", 0),
            new CalcButton(jButtonArcSin, "arcSine", 1, "sin⁻¹ ", 10),
            new CalcButton(jButtonLog10, "log", 1, "log ", 10),
            new CalcButton(jButtonClrInput, "clearInput", 4, "", 0),
            new CalcButton(jButtonDel, "delete", 4, "", 0),
            new CalcButton(jButtonLog, "nLog", 1, "ln ", 10),
            new CalcButton(jButton5, "five", 0, "5", 0),
            new CalcButton(jButton0, "zero", 0, "0", 0),
            new CalcButton(jButtonPlus, "plus", 2, " + ", 5),
            new CalcButton(jButton4, "four", 0, "4", 0),
            new CalcButton(jButtonRoot, "root", 2, "√", 10),
            new CalcButton(jButtonArcCos, "arcCosine", 1, "cos⁻¹ ", 10),
            new CalcButton(jButtonArcTan, "arcTangent", 1, "tan⁻¹ ", 10),
            new CalcButton(jButtonEqual, "equal", 4, " =", 0),
            new CalcButton(jButtonSin, "sine", 1, "sin ", 10)};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        keyPad = new javax.swing.JPanel();
        jButtonEuler = new javax.swing.JButton();
        jButtonInvLog10 = new javax.swing.JButton();
        jButtonLog10 = new javax.swing.JButton();
        jButtonOpenBrack = new javax.swing.JButton();
        jButtonCloseBrack = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();
        jButtonClrInput = new javax.swing.JButton();
        jButtonClrAll = new javax.swing.JButton();
        jButtonLog = new javax.swing.JButton();
        jButtonRoot = new javax.swing.JButton();
        jButtonExp = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonDiv = new javax.swing.JButton();
        jButtonInv = new javax.swing.JButton();
        jButtonCos = new javax.swing.JButton();
        jButtonSin = new javax.swing.JButton();
        jButtonTan = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButtonMult = new javax.swing.JButton();
        jButtonSqr = new javax.swing.JButton();
        jButtonArcSin = new javax.swing.JButton();
        jButtonArcCos = new javax.swing.JButton();
        jButtonArcTan = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jButtonSqrt = new javax.swing.JButton();
        jToggleButtonDegRad = new javax.swing.JToggleButton();
        jButtonPI = new javax.swing.JButton();
        jButtonFact = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonPM = new javax.swing.JButton();
        jButtonDecPoint = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButtonEqual = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelExpression = new javax.swing.JLabel();
        jLabelDisplay = new javax.swing.JLabel();
        jLabelDegRadToggle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBounds(new java.awt.Rectangle(50, 50, 600, 400));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(500, 350));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jSeparator1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        keyPad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.setLayout(new java.awt.GridLayout(5, 11, 1, 1));

        jButtonEuler.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 13)); // NOI18N
        jButtonEuler.setText("eˣ");
        jButtonEuler.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonEuler.setName("keypad"); // NOI18N
        jButtonEuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEulerActionPerformed(evt);
            }
        });
        jButtonEuler.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonEuler);

        jButtonInvLog10.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 13)); // NOI18N
        jButtonInvLog10.setText("10ˣ");
        jButtonInvLog10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonInvLog10.setName("keypad"); // NOI18N
        jButtonInvLog10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInvLog10ActionPerformed(evt);
            }
        });
        jButtonInvLog10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonInvLog10);

        jButtonLog10.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 13)); // NOI18N
        jButtonLog10.setText("log₁₀");
        jButtonLog10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonLog10.setName("keypad"); // NOI18N
        jButtonLog10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLog10ActionPerformed(evt);
            }
        });
        jButtonLog10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonLog10);

        jButtonOpenBrack.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 14)); // NOI18N
        jButtonOpenBrack.setText("(");
        jButtonOpenBrack.setToolTipText("");
        jButtonOpenBrack.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonOpenBrack.setName("keypad"); // NOI18N
        jButtonOpenBrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenBrackActionPerformed(evt);
            }
        });
        jButtonOpenBrack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonOpenBrack);

        jButtonCloseBrack.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 14)); // NOI18N
        jButtonCloseBrack.setText(")");
        jButtonCloseBrack.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonCloseBrack.setName("keypad"); // NOI18N
        jButtonCloseBrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseBrackActionPerformed(evt);
            }
        });
        jButtonCloseBrack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonCloseBrack);

        jButtonDel.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 12)); // NOI18N
        jButtonDel.setText("DEL");
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });
        jButtonDel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonDel);

        jButtonClrInput.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 12)); // NOI18N
        jButtonClrInput.setText("CE");
        jButtonClrInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClrInputActionPerformed(evt);
            }
        });
        jButtonClrInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonClrInput);

        jButtonClrAll.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 12)); // NOI18N
        jButtonClrAll.setText("C");
        jButtonClrAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClrAllActionPerformed(evt);
            }
        });
        jButtonClrAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonClrAll);

        jButtonLog.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 13)); // NOI18N
        jButtonLog.setText("ln");
        jButtonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogActionPerformed(evt);
            }
        });
        jButtonLog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonLog);

        jButtonRoot.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 14)); // NOI18N
        jButtonRoot.setText("ʸ√x");
        jButtonRoot.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonRoot.setName("keypad"); // NOI18N
        jButtonRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRootActionPerformed(evt);
            }
        });
        jButtonRoot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonRoot);

        jButtonExp.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 14)); // NOI18N
        jButtonExp.setText("xʸ");
        jButtonExp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonExp.setName("keypad"); // NOI18N
        jButtonExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExpActionPerformed(evt);
            }
        });
        jButtonExp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonExp);

        jButton7.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 1, 18)); // NOI18N
        jButton7.setText("7");
        jButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton7.setName("keypad"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButton7);

        jButton8.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 1, 18)); // NOI18N
        jButton8.setText("8");
        jButton8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton8.setName("keypad"); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jButton8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButton8);

        jButton9.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 1, 18)); // NOI18N
        jButton9.setText("9");
        jButton9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton9.setName("keypad"); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jButton9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButton9);

        jButtonDiv.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 14)); // NOI18N
        jButtonDiv.setText("/");
        jButtonDiv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonDiv.setName("keypad"); // NOI18N
        jButtonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivActionPerformed(evt);
            }
        });
        jButtonDiv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonDiv);

        jButtonInv.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 14)); // NOI18N
        jButtonInv.setText("1/x");
        jButtonInv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonInv.setName("keypad"); // NOI18N
        jButtonInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInvActionPerformed(evt);
            }
        });
        jButtonInv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonInv);

        jButtonCos.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 13)); // NOI18N
        jButtonCos.setText("cos");
        jButtonCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCosActionPerformed(evt);
            }
        });
        jButtonCos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonCos);

        jButtonSin.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 13)); // NOI18N
        jButtonSin.setText("sin");
        jButtonSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinActionPerformed(evt);
            }
        });
        jButtonSin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonSin);

        jButtonTan.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 13)); // NOI18N
        jButtonTan.setText("tan");
        jButtonTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTanActionPerformed(evt);
            }
        });
        jButtonTan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonTan);

        jButton4.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 1, 18)); // NOI18N
        jButton4.setText("4");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.setName("keypad"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButton4);

        jButton5.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 1, 18)); // NOI18N
        jButton5.setText("5");
        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton5.setName("keypad"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButton5);

        jButton6.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 1, 18)); // NOI18N
        jButton6.setText("6");
        jButton6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton6.setName("keypad"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButton6);

        jButtonMult.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 14)); // NOI18N
        jButtonMult.setText("*");
        jButtonMult.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonMult.setName("keypad"); // NOI18N
        jButtonMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultActionPerformed(evt);
            }
        });
        jButtonMult.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonMult);

        jButtonSqr.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 14)); // NOI18N
        jButtonSqr.setText("x²");
        jButtonSqr.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonSqr.setName("keypad"); // NOI18N
        jButtonSqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSqrActionPerformed(evt);
            }
        });
        jButtonSqr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonSqr);

        jButtonArcSin.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 13)); // NOI18N
        jButtonArcSin.setText("sin⁻¹");
        jButtonArcSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArcSinActionPerformed(evt);
            }
        });
        jButtonArcSin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonArcSin);

        jButtonArcCos.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 13)); // NOI18N
        jButtonArcCos.setText("cos⁻¹");
        jButtonArcCos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonArcCos.setName("keypad"); // NOI18N
        jButtonArcCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArcCosActionPerformed(evt);
            }
        });
        jButtonArcCos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonArcCos);

        jButtonArcTan.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 13)); // NOI18N
        jButtonArcTan.setText("tan⁻¹");
        jButtonArcTan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonArcTan.setName("keypad"); // NOI18N
        jButtonArcTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArcTanActionPerformed(evt);
            }
        });
        jButtonArcTan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonArcTan);

        jButton1.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 1, 18)); // NOI18N
        jButton1.setText("1");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setName("keypad"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButton1);

        jButton2.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 1, 18)); // NOI18N
        jButton2.setText("2");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.setName("keypad"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButton2);

        jButton3.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 1, 18)); // NOI18N
        jButton3.setText("3");
        jButton3.setActionCommand("");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.setName("keypad"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButton3);

        jButtonMinus.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 14)); // NOI18N
        jButtonMinus.setText("—");
        jButtonMinus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonMinus.setName("keypad"); // NOI18N
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });
        jButtonMinus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonMinus);

        jButtonSqrt.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 14)); // NOI18N
        jButtonSqrt.setText("√x");
        jButtonSqrt.setToolTipText("");
        jButtonSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSqrtActionPerformed(evt);
            }
        });
        jButtonSqrt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonSqrt);

        jToggleButtonDegRad.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 12)); // NOI18N
        jToggleButtonDegRad.setText("DEG");
        jToggleButtonDegRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonDegRadActionPerformed(evt);
            }
        });
        jToggleButtonDegRad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jToggleButtonDegRad);

        jButtonPI.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 13)); // NOI18N
        jButtonPI.setText("π");
        jButtonPI.setToolTipText("");
        jButtonPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPIActionPerformed(evt);
            }
        });
        jButtonPI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonPI);

        jButtonFact.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 13)); // NOI18N
        jButtonFact.setText("n!");
        jButtonFact.setToolTipText("");
        jButtonFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFactActionPerformed(evt);
            }
        });
        jButtonFact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonFact);

        jButton0.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 1, 18)); // NOI18N
        jButton0.setText("0");
        jButton0.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton0.setName("keypad"); // NOI18N
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        jButton0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButton0);

        jButtonPM.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 14)); // NOI18N
        jButtonPM.setText("±");
        jButtonPM.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonPM.setName("keypad"); // NOI18N
        jButtonPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPMActionPerformed(evt);
            }
        });
        jButtonPM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonPM);

        jButtonDecPoint.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 14)); // NOI18N
        jButtonDecPoint.setText("·");
        jButtonDecPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecPointActionPerformed(evt);
            }
        });
        jButtonDecPoint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonDecPoint);

        jButtonPlus.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 0, 14)); // NOI18N
        jButtonPlus.setText("+");
        jButtonPlus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonPlus.setName("keypad"); // NOI18N
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });
        jButtonPlus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonPlus);

        jButtonEqual.setFont(new java.awt.Font("CMU Typewriter Text Variable Wi", 1, 18)); // NOI18N
        jButtonEqual.setText("=");
        jButtonEqual.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonEqual.setName("keypad"); // NOI18N
        jButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualActionPerformed(evt);
            }
        });
        jButtonEqual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        keyPad.add(jButtonEqual);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255)));

        jLabelExpression.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabelExpression.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelExpression.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabelDisplay.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabelDisplay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDisplay.setToolTipText("");
        jLabelDisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabelDegRadToggle.setText("D");
        jLabelDegRadToggle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelDegRadToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelExpression, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelExpression, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDegRadToggle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keyPad, javax.swing.GroupLayout.PREFERRED_SIZE, 490, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keyPad, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOpenBrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenBrackActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[18]);
    }//GEN-LAST:event_jButtonOpenBrackActionPerformed

    private void jButtonExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExpActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[23]);
    }//GEN-LAST:event_jButtonExpActionPerformed

    private void jButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[37]);
    }//GEN-LAST:event_jButtonEqualActionPerformed

    private void jToggleButtonDegRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonDegRadActionPerformed
        // TODO add your handling code here:
        evt.getID();
        toggleDegRad();
    }//GEN-LAST:event_jToggleButtonDegRadActionPerformed

    private void jButtonEulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEulerActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[4]);
    }//GEN-LAST:event_jButtonEulerActionPerformed

    private void jButtonClrInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClrInputActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[27]);
    }//GEN-LAST:event_jButtonClrInputActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[24]);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButtonDecPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecPointActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[10]);
    }//GEN-LAST:event_jButtonDecPointActionPerformed

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[32]);
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void jButtonPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPMActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[17]);
    }//GEN-LAST:event_jButtonPMActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[31]);
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFactActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[9]);
    }//GEN-LAST:event_jButtonFactActionPerformed

    private void jButtonPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPIActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[8]);
    }//GEN-LAST:event_jButtonPIActionPerformed

    private void jButtonSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSqrtActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[5]);
    }//GEN-LAST:event_jButtonSqrtActionPerformed

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[22]);
    }//GEN-LAST:event_jButtonMinusActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[19]);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[6]);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[0]);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonArcTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArcTanActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[36]);
    }//GEN-LAST:event_jButtonArcTanActionPerformed

    private void jButtonArcCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArcCosActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[35]);
    }//GEN-LAST:event_jButtonArcCosActionPerformed

    private void jButtonArcSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArcSinActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[25]);
    }//GEN-LAST:event_jButtonArcSinActionPerformed

    private void jButtonSqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSqrActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[15]);
    }//GEN-LAST:event_jButtonSqrActionPerformed

    private void jButtonMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[16]);
    }//GEN-LAST:event_jButtonMultActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[1]);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[30]);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[33]);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTanActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[21]);
    }//GEN-LAST:event_jButtonTanActionPerformed

    private void jButtonSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[38]);
    }//GEN-LAST:event_jButtonSinActionPerformed

    private void jButtonCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCosActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[20]);
    }//GEN-LAST:event_jButtonCosActionPerformed

    private void jButtonInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInvActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[13]);
    }//GEN-LAST:event_jButtonInvActionPerformed

    private void jButtonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[2]);
    }//GEN-LAST:event_jButtonDivActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[11]);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[7]);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButtonRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRootActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[34]);
    }//GEN-LAST:event_jButtonRootActionPerformed

    private void jButtonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[29]);
    }//GEN-LAST:event_jButtonLogActionPerformed

    private void jButtonClrAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClrAllActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[12]);
    }//GEN-LAST:event_jButtonClrAllActionPerformed

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[28]);
    }//GEN-LAST:event_jButtonDelActionPerformed

    private void jButtonCloseBrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseBrackActionPerformed
        // TODO add your handling code here:c
        evt.getID();
        inputListener.action(buttons[3]);
    }//GEN-LAST:event_jButtonCloseBrackActionPerformed

    private void jButtonLog10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLog10ActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[26]);
    }//GEN-LAST:event_jButtonLog10ActionPerformed

    private void jButtonInvLog10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInvLog10ActionPerformed
        // TODO add your handling code here:
        evt.getID();
        inputListener.action(buttons[14]);
    }//GEN-LAST:event_jButtonInvLog10ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        switch (evt.getKeyChar()) {
            case 'e':
                inputListener.action(buttons[4]);
                break;
            case 'E':
                inputListener.action(buttons[14]);
                break;
            case 'c':
            case 'C':
                inputListener.action(buttons[20]);
                break;
            case 'd':
                inputListener.action(buttons[2]);
                break;
            case 'D':
                toggleDegRad();
                break;
            case 'f':
            case 'F':
                inputListener.action(buttons[9]);
                break;
            case 'i':
            case 'I':
                inputListener.action(buttons[13]);
                break;
            case 'l':
                inputListener.action(buttons[29]);
                break;
            case 'L':
                inputListener.action(buttons[29]);
                break;
            case 'o':
            case 'O':
            case '0':
                inputListener.action(buttons[31]);
                break;
            case 'p':
            case 'P':
                inputListener.action(buttons[8]);
                break;
            case 'q':
            case 'Q':
                this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
                break;
            case 'r':
                inputListener.action(buttons[5]);
                break;
            case 'R':
                inputListener.action(buttons[34]);
                break;
            case 's':
                inputListener.action(buttons[38]);
                break;
            case 'S':
                inputListener.action(buttons[25]);
                break;
            case 't':
            case 'T':
                inputListener.action(buttons[21]);
                break;
            case 'x':
            case 'X':
                inputListener.action(buttons[16]);
                break;

            case '²':
                inputListener.action(buttons[15]);
                break;
            case '.':
                inputListener.action(buttons[10]);
                break;
            case '^':
                inputListener.action(buttons[23]);
                break;
            case '*':
                inputListener.action(buttons[16]);
                break;
            case '/':
                inputListener.action(buttons[2]);
                break;
            case '+':
                inputListener.action(buttons[32]);
                break;

            case '-':
                inputListener.action(buttons[22]);
                break;
            case '=':
                inputListener.action(buttons[37]);
                break;
            case '(':
                inputListener.action(buttons[18]);
                break;
            case ')':
                inputListener.action(buttons[3]);
                break;
            case '!':
                inputListener.action(buttons[9]);
                break;
            case '1':
                inputListener.action(buttons[0]);
                break;
            case '2':
                inputListener.action(buttons[6]);
                break;
            case '3':
                inputListener.action(buttons[19]);
                break;
            case '4':
                inputListener.action(buttons[33]);
                break;

            case '5':
                inputListener.action(buttons[30]);
                break;

            case '6':
                inputListener.action(buttons[1]);
                break;
            case '7':
                inputListener.action(buttons[7]);
                break;
            case '8':
                inputListener.action(buttons[24]);
                break;
            case '9':
                inputListener.action(buttons[11]);
                break;
            case '\b':
                inputListener.action(buttons[28]);
                break;
            case '\r':
                inputListener.action(buttons[37]);
                break;
            case '\n':
                inputListener.action(buttons[37]);
                break;
        }
    }//GEN-LAST:event_formKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JavaCalculator().setVisible(true);
        });
    }
    InputListener inputListener;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonArcCos;
    private javax.swing.JButton jButtonArcSin;
    private javax.swing.JButton jButtonArcTan;
    private javax.swing.JButton jButtonCloseBrack;
    private javax.swing.JButton jButtonClrAll;
    private javax.swing.JButton jButtonClrInput;
    private javax.swing.JButton jButtonCos;
    private javax.swing.JButton jButtonDecPoint;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonDiv;
    private javax.swing.JButton jButtonEqual;
    private javax.swing.JButton jButtonEuler;
    private javax.swing.JButton jButtonExp;
    private javax.swing.JButton jButtonFact;
    private javax.swing.JButton jButtonInv;
    private javax.swing.JButton jButtonInvLog10;
    private javax.swing.JButton jButtonLog;
    private javax.swing.JButton jButtonLog10;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonMult;
    private javax.swing.JButton jButtonOpenBrack;
    private javax.swing.JButton jButtonPI;
    private javax.swing.JButton jButtonPM;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JButton jButtonRoot;
    private javax.swing.JButton jButtonSin;
    private javax.swing.JButton jButtonSqr;
    private javax.swing.JButton jButtonSqrt;
    private javax.swing.JButton jButtonTan;
    public static javax.swing.JLabel jLabelDegRadToggle;
    private javax.swing.JLabel jLabelDisplay;
    private javax.swing.JLabel jLabelExpression;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton jToggleButtonDegRad;
    private javax.swing.JPanel keyPad;
    // End of variables declaration//GEN-END:variables
    final CalcButton[] buttons;

    private void toggleDegRad() {
        if (jLabelDegRadToggle.getText().equals("D")) {
            jLabelDegRadToggle.setText("R");
            jToggleButtonDegRad.setText("RAD");
        } else {
            jLabelDegRadToggle.setText("D");
            jToggleButtonDegRad.setText("DEG");
        }
    }
}
